require 'datastructures/version'
require 'datastructures/queue'
require 'datastructures/priority_queue'
require 'datastructures/stack'
require 'datastructures/tree_node'
require 'datastructures/linked_list'
require 'datastructures/adjacency_list'